services:
  az-proxy:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: az-proxy
    ports:
      - "4003:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml:ro
    command:
      - "--config"
      - "/app/config.yaml"
    environment:
      - GITHUB_TOKEN_1=${GITHUB_TOKEN_1}
      - GITHUB_TOKEN_2=${GITHUB_TOKEN_2}
      - GITHUB_TOKEN_3=${GITHUB_TOKEN_3}
      - GITHUB_TOKEN_4=${GITHUB_TOKEN_4}
      - GITHUB_TOKEN_5=${GITHUB_TOKEN_5}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - STORE_MODEL_IN_DB=False
    restart: unless-stopped
