router_settings:
  routing_strategy: simple-shuffle
  num_retries: 3
  retry_after: 5

litellm_settings:
  set_verbose: false
  drop_params: true

model_list:

  - model_name: deepseek-v3
    litellm_params:
      model: openai/DeepSeek-V3.2-Speciale
      api_base: https://llm-development-artifacts.services.ai.azure.com/models
      api_key: os.environ/AZURE_AI_KEY
